name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint
      - name: Run lint
        run: |
          golint -set_exit_status $(go list ./...)
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go get -t -v ./...
      - name: Run tests
        run: |
          go test -v ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          go build -o myapp
